apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-volume-node-cleanup-controller
  namespace: default

---
# CleanupController must be able to work with PVs, PVCs and Nodes.
# It also emits events before PVC deletion.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-volume-node-cleanup-controller-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-volume-node-cleanup-controller-role
subjects:
  - kind: ServiceAccount
    name: local-volume-node-cleanup-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: local-volume-node-cleanup-controller-runner
  apiGroup: rbac.authorization.k8s.io
