loki:
  auth_enabled: false
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  
  storage:
    bucketNames:
      chunks: ${bucketname}
      ruler: ${bucketname}
      admin: ${bucketname}
    type: s3
    s3:
      region: ${region}
      bucketnames: ${bucketname}
      s3forcepathstyle: false
      s3ForcePathStyle: false
      insecure: false
  env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  memberlist:
    bind_addr:
    - $${MY_POD_IP}
  schemaConfig:
    configs:
    - from: "2020-05-15"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        period: 24h
        prefix: loki_index_

#   querier:
#     query_timeout: 5m
#     engine:
#       timeout: 5m
#     max_concurrent: 50
  server:
    grpc_server_max_recv_msg_size: 52428800
    http_server_read_timeout: 300s
    http_server_write_timeout: 300s

  query_scheduler:
    max_outstanding_requests_per_tenant: 4096
  frontend:
    max_outstanding_per_tenant: 4096
  query_range:
    parallelise_shardable_queries: true
  limits_config:
    query_timeout: 5m
    split_queries_by_interval: 15m
    max_query_parallelism: 3500
    max_query_series: 50000
    allow_structured_metadata: false
  memcached:
    chunk_cache:
      enabled: ${enable_memcache_chunk}
      addresses: memcached-chunk.memcached-chunk.svc.cluster.local:11211
      service: memcached-chunk
      batch_size: 256
      parallelism: 10
    results_cache:
      enabled: ${enable_memcache_result}
      addresses: memcached-result.memcached-result.svc.cluster.local:11211
      service: memcached-result
      default_validity: 12h

serviceAccount:
  create: true
  name: ${sa_name}
  imagePullSecrets: []
  labels: {}
  annotations:
    eks.amazonaws.com/role-arn: "${irsa_arn}"
  automountServiceAccountToken: true

write:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  
  affinity: {}
  persistence:
    enableStatefulSetAutoDeletePVC: true
    storageClass: openebs-hostpath-xfs
    size: 100Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  # nodeSelector:
  #   large: "true"

read:
  affinity: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  

backend:
  affinity: {}
  persistence:
    enableStatefulSetAutoDeletePVC: true
    storageClass: openebs-hostpath-xfs
    size: 100Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  

gateway:
  affinity: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  

singleBinary:
  affinity: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  

monitoring:
  lokiCanary:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  

tableManager:
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"  
sidecar:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi